export const projectStatusOptions = [
  "Em elaboração",
  "Aguardando documentos",
  "Em revisão",
  "Pronto para envio",
  "Enviado",
  "Em análise documental",
  "Em diligência",
  "Diligência respondida",
  "Em análise técnica",
  "Aprovado",
  "Aprovado com ressalvas",
  "Não aprovado",
  "Recurso apresentado",
  "Recurso deferido",
  "Recurso indeferido",
  "Aguardando autorização para captar",
  "Captação aberta",
  "Captação parcial",
  "Captação concluída",
  "Prazo de captação encerrado",
  "Aguardando assinatura",
  "Em execução",
  "Prestação de contas parcial",
  "Prestação de contas final",
  "Prestação aprovada",
  "Projeto encerrado",
  "Prestação reprovada",
  "Arquivado"
];

export const projectTypeOptions = [
  "Lei Rouanet",
  "Lei de Incentivo ao Esporte",
  "FIA",
  "Fundo da Pessoa Idosa",
  "Funcultura",
  "PNAB",
  "Ministério da Cultura",
  "Ministério do Esporte",
  "Ministério da Justiça",
  "Ministério da Saúde",
  "Ministério da Educação",
  "Petrobras",
  "Banco do Nordeste",
  "BNDES",
  "Itaú Social",
  "Fundação Banco do Brasil",
  "Instituto Phi",
  "Emenda Parlamentar",
  "Convênio Federal",
  "Convênio Estadual",
  "Convênio Municipal",
  "Patrocínio Direto",
  "Outro"
];
